spring:
  datasource:
    url: jdbc:mysql://localhost:3306/journaldb
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    hibernate:
      ddl-auto: update


