spring:
  redis:
    host: redis-16561.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 16561
    password: OtA3ch3B3clAfxgnf9htBRmSWJknyJR1
#      database: 0
#      timeout: 0
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1