spring:
  profiles:
    active:
      - ansi
#      - logging
      - atlas-uy
      - weather-api
      - mail
      - redis-cloud
      - redpanda-cloud

  config:
    additional-location: classpath:config/

server:
  port: 8080
